Repository cave-story-randomizer/cave-story-randomizer, pull requests merged in 2019-03, with the labels that each got.

#16 applies game focus hack by Clownacy/Txin
  pre-edited-cs/Doukutsu.exe
Labels: Cave Story

#28 Improves Balrog 1
  pre-edited-cs/data/Stage/Barr.pxe
  pre-edited-cs/data/Stage/Barr.pxm
  pre-edited-cs/data/Stage/Barr.tsc
  pre-edited-cs/data/Stage/Mimi.pxa
  pre-edited-cs/data/Stage/PrtMimi.bmp
  pre-edited-cs/data/Stage/ScriptSource/Barr.txt
  src/database/items.lua
Labels: Bug, Cave Story, QOL, Randomizer

#32 Fixes most softlock issues
  pre-edited-cs/data/Stage/Cave.tsc
  pre-edited-cs/data/Stage/CentW.tsc
  pre-edited-cs/data/Stage/Chako.tsc
  pre-edited-cs/data/Stage/Curly.pxe
  pre-edited-cs/data/Stage/MazeM.pxm
  pre-edited-cs/data/Stage/Pole.tsc
  pre-edited-cs/data/Stage/Sand.pxm
  pre-edited-cs/data/Stage/ScriptSource/Cave.txt
  pre-edited-cs/data/Stage/ScriptSource/CentW.txt
  pre-edited-cs/data/Stage/ScriptSource/Chako.txt
  pre-edited-cs/data/Stage/ScriptSource/Pole.txt
  src/database/world_graph.lua
Labels: Cave Story, Softlock, Text Issue

#31 fixes issue #7 "ma pignon's chest item can be obtained over and over"
  pre-edited-cs/data/Stage/Mapi.pxe
  pre-edited-cs/data/Stage/Mapi.tsc
  pre-edited-cs/data/Stage/ScriptSource/Mapi.txt
Labels: Cave Story

#34 fixes #11, broken sprinkler can give infinite items
  pre-edited-cs/data/Stage/Cent.pxe
  pre-edited-cs/data/Stage/Cent.tsc
  pre-edited-cs/data/Stage/ScriptSource/Cent.txt
Labels: Bug/Fix

#38 fixes #36, fixes #37 - balcony barrier issues
  pre-edited-cs/data/Stage/Blcny1.pxe
  pre-edited-cs/data/Stage/Blcny1.tsc
  pre-edited-cs/data/Stage/ScriptSource/Blcny1.txt
Labels: Bug/Fix, Cave Story, QOL

#39 fixes #14, egg 2 issues, and improves egg no 0 when entering from wall
  pre-edited-cs/data/Stage/EggX2.tsc
  pre-edited-cs/data/Stage/Eggs2.tsc
  pre-edited-cs/data/Stage/Oside.tsc
  pre-edited-cs/data/Stage/ScriptSource/EggX2.txt
  pre-edited-cs/data/Stage/ScriptSource/Eggs2.txt
  pre-edited-cs/data/Stage/ScriptSource/Oside.txt
Labels: Bug/Fix, Cave Story, QOL

#40 fixes #13, #15 - santa key and hell 1
  pre-edited-cs/data/Stage/Hell1.pxe
  pre-edited-cs/data/Stage/Hell1.tsc
  pre-edited-cs/data/Stage/ScriptSource/Hell1.txt
  pre-edited-cs/data/Stage/Weed.pxe
  pre-edited-cs/data/Stage/Weed.tsc
Labels: Bug/Fix, Cave Story, QOL

#41 fixes #5, fixes #24, fixes #30
  pre-edited-cs/data/Head.tsc
  pre-edited-cs/data/ScriptSource/Head.txt
  pre-edited-cs/data/Stage/Cemet.tsc
  pre-edited-cs/data/Stage/Little.tsc
  pre-edited-cs/data/Stage/MazeA.tsc
  pre-edited-cs/data/Stage/Pens1.tsc
  pre-edited-cs/data/Stage/ScriptSource/Cemet.txt
  pre-edited-cs/data/Stage/ScriptSource/Little.txt
  pre-edited-cs/data/Stage/ScriptSource/MazeA.txt
  pre-edited-cs/data/Stage/ScriptSource/Pens1.txt
Labels: Bug/Fix, Cave Story, Feature, QOL

#42 fixes #25, fixes #8 - core water issues
  pre-edited-cs/data/Stage/Almond.pxe
  pre-edited-cs/data/Stage/Almond.tsc
  pre-edited-cs/data/Stage/Drain.tsc
  pre-edited-cs/data/Stage/ScriptSource/Almond.txt
  pre-edited-cs/data/Stage/ScriptSource/Drain.txt
Labels: Bug/Fix, Cave Story, Softlock

#46 core/puppy chest hotfix
  pre-edited-cs/Doukutsu.exe
  pre-edited-cs/data/Stage/Almond.tsc
  pre-edited-cs/data/Stage/Sand.pxe
  pre-edited-cs/data/Stage/Sand.tsc
  pre-edited-cs/data/Stage/ScriptSource/Almond.txt
  pre-edited-cs/data/Stage/ScriptSource/Sand.txt
Labels: Bug/Fix, Cave Story, Softlock
